# Generated by Django 5.1.3 on 2024-11-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=70)),
                ('psot_title', models.TextField(max_length=150)),
                ('discriptions', models.TimeField(max_length=200)),
            ],
        ),
    ]
